version: "3.3"

services:
  main:
    build: .
    restart: on-failure
    environment:
      - PYTHONUNBUFFERED=1
      - NIGHTSCOUT_URL=https://beltrandt1.herokuapp.com
      - PHILLIPS_IP=10.0.0.6
      - PHILLIPS_USERNAME=9h22tnFIlBdqimx8jRpYeT3Qy7m0Lf-dMRqknFVK
      - BRIGHTNESS_LEVEL=250
      - LIGHT_ID=1
      - HIGH_GLUCOSE_VALUE=200
      - HIGH_COLOR=RED
      - RANGE_COLOR=GREEN
      - LOW_COLOR=BLUE
      - LOW_GLUCOSE_VALUE=80
      - START_TIME=8:00
      - END_TIME=22:00
      - TIMEZONE_DIFFERENCE=+2
      - REFRESH_RATE=60
      - NIGHTSCOUT_REALTIME_DIFFERENCE="30 minutes"
      - LOCAL_MODE=FALSE
      - TOKEN=FALSE